name = "ArtifactWrappers"
uuid = "a14bc488-3040-4b00-9dc1-f6467924858a"
authors = ["Climate Modeling Alliance"]
version = "0.1.2"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Downloads = "1.4.0"
julia = "1.3"
